# Generated by Django 4.0.2 on 2022-02-26 08:36

import config.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_alter_about_id_alter_aboutmaydon_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='title',
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, upload_to=config.helpers.upload_file_name),
        ),
        migrations.AlterField(
            model_name='futuremodels',
            name='image',
            field=models.ImageField(blank=True, upload_to=config.helpers.upload_file_name),
        ),
        migrations.AlterField(
            model_name='mainsitemodels',
            name='image',
            field=models.ImageField(blank=True, upload_to=config.helpers.upload_file_name),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(upload_to=config.helpers.upload_file_name),
        ),
        migrations.AlterField(
            model_name='xodimmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to=config.helpers.upload_file_name),
        ),
    ]
