# Generated by Django 4.0.2 on 2022-02-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0030_remove_newsmodel_title_alter_about_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
